name: white
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  photo_view:
  flutter_rating_bar:
  table_calendar:
  flutter_calendar_carousel:
  modal_progress_hud:
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  shared_preferences: ^0.5.7+3
  cloud_firestore: ^0.13.6
  firebase_core: ^0.4.5
  font_awesome_flutter:
  google_maps_flutter: ^0.5.28+1
  provider: ^4.1.2
  firebase_messaging: ^6.0.16
  flutter_local_notifications: ^1.4.4
  path_provider: ^1.6.10
  image_picker: ^0.6.7
  image_cropper: ^1.2.2
  flutter_svg: ^0.17.4
  rxdart: ^0.24.1
  intl: ^0.16.1
  http: ^0.12.1
  webview_flutter: ^0.3.22+1
  firebase_storage: ^3.1.6
  cached_network_image: ^2.2.0+1
  fluttertoast: ^4.0.1
  geolocator: ^5.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/imagesH/photo.png
    - assets/imagesH/photo-1.png
    - assets/imagesH/photo-2.png
    - assets/imagesH/photo-3.png
    - assets/imagesH/photo-4.png
    - assets/imagesH/photo-5.png
    - assets/images/mahmoud.jpg
    - assets/images/mahmoud.jpg
    - assets/images/Logo.svg
    - assets/images/Logo.png
    - assets/imagesH/google-icon.png
    - assets/imagesH/facebook_icon.png
    - assets/galleryImages/
    - assets/images/university.jpg
    - assets/images/uni.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: mvboli
      fonts:
        - asset: assets/fonts/mvboli.ttf
          style: italic
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
